# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ConflateRoads
                                 A QGIS plugin
 This plugin conflates road network datasets by matching road segments using geometric and topological similarity metrics, then transfers selected attributes from a reference dataset to a target dataset.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-07-28
        copyright            : (C) 2026 by Philip Nyakwaka
        email                : philipnyakwaka24@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ConflateRoads class from file ConflateRoads.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .conflate_roads import ConflateRoads
    return ConflateRoads(iface)
