# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ConflateRoads
                                 A QGIS plugin
 This plugin conflates road network datasets by matching road segments using geometric and topological similarity metrics, then transfers selected attributes from a reference dataset to a target dataset.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-07-28
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Philip Nyakwaka
        email                : philipnyakwaka24@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from conflate_roads.tasks import ConflationTask
from .exceptions import ConflationCancelledException
from .resources import *
from qgis.PyQt.QtCore import QLocale, QTranslator, QCoreApplication, Qt
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QMessageBox, QMessageBox, QProgressDialog
from qgis.core import (
    QgsSettings, QgsVectorFileWriter, Qgis,
    QgsProject, QgsVectorLayer, QgsApplication
)

# Import the code for the dialog
from .conflate_roads_dialog import ConflateRoadsDialog
import os.path


class ConflateRoads:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QgsSettings().value('locale/userLocale', QLocale().name())[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            '{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Conflate Roads')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('ConflateRoads', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToVectorMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = os.path.join(os.path.dirname(__file__), 'icon.png')
        self.add_action(
            icon_path,
            text=self.tr(u'Road Network Conflation'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginVectorMenu(
                self.tr(u'&Conflate Roads'),
                action)
            self.iface.removeToolBarIcon(action)

    def conflation_finished(self, task, output_path, progress):
        """custom callback function to handle the completion of the conflation task"""
        progress.close()

        # If the task completed successfully, write the output to the specified file format
        driver = "GPKG" if output_path.lower().endswith('.gpkg') else \
            "ESRI Shapefile" if output_path.lower().endswith('.shp') else "GeoJSON"
        options = QgsVectorFileWriter.SaveVectorOptions()
        options.driverName = driver
        options.fileEncoding = "UTF-8"
        options.actionOnExistingFile = QgsVectorFileWriter.CreateOrOverwriteLayer
        
        result = QgsVectorFileWriter.writeAsVectorFormatV3(
            task.destination_layer,
            output_path,
            QgsProject.instance().transformContext(),
            options
        )

        if result[0] == QgsVectorFileWriter.NoError:
            self.iface.messageBar().pushMessage(
                "Success",
                "Road conflation completed successfully",
                level=Qgis.Success,
                duration=5
            )

            reply = QMessageBox.question(
                self.dlg,
                "Conflation Complete",
                "The road networks have been successfully conflated.\n\n"
                f'Total features: {task.match_stats["total_features"]}\n'
                f'Matched features: {task.match_stats["matched_features"]}\n'
                f'Unmatched features: {task.match_stats["unmatched_features"]}\n\n'
                f"The output has been saved to:\n{output_path}\n\n"
                "Would you like to add the output layer to the current project?",
                QMessageBox.Yes | QMessageBox.No,
                QMessageBox.Yes
            )

            if reply == QMessageBox.Yes:
                layer_name = os.path.splitext(os.path.basename(output_path))[0]

                layer = QgsVectorLayer(output_path, layer_name, "ogr")

                if layer.isValid():
                    QgsProject.instance().addMapLayer(layer)
                else:
                    QMessageBox.critical(
                        self.dlg,
                        "Layer Load Failed",
                        "The output was created successfully, but it could not be added to the project."
                    )
        else:
            self.iface.messageBar().pushMessage(
                "Output Failed",
                "The conflation completed, but the output could not be saved.",
                level=Qgis.Critical,
                duration=0
            )
            QMessageBox.critical(
                self.dlg,
                "Output Failed",
                "The conflation completed, but the output could not be saved."
                f"Error code: {result[0]}\n\n"
                f"Error message:\n{result[1]}"
            )   

    def conflation_terminated(self, task, progress):
        """custom callback function to handle the termination of the conflation task"""
        progress.close()
        
        if isinstance(task.exception, ConflationCancelledException):
            self.iface.messageBar().pushMessage(
                "Conflation Cancelled",
                "The conflation process was cancelled. "
                "Changes have been rolled back.",
                level=Qgis.Warning,
                duration=8
            )

            QMessageBox.warning(
                self.dlg,
                "Conflation Cancelled",
                "The conflation process was cancelled.\n\n"
                "All changes have been rolled back."
            )
            return
        
        if task.exception is not None:
            self.iface.messageBar().pushMessage(
                "Conflation Failed",
                str(task.exception),
                level=Qgis.Critical,
                duration=0
            )
            QMessageBox.critical(
                self.dlg,
                "Conflation Failed",
                str(task.exception)
            )
    
    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = ConflateRoadsDialog()

        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            source_layer = self.dlg.cmbSourceLayer.currentLayer().clone()  # Copy to avoid modifying the original layer
            destination_layer = self.dlg.cmbDestinationLayer.currentLayer().clone()  # Copy to avoid modifying the original layer
            attributes = self.dlg.cmbAttributes.checkedItems()
            road_pattern = self.dlg.cmbRoadPattern.currentText()
            threshold = self.dlg.spnSearchBuffer.value()
            output_path = self.dlg.txtOutputFile.text()

            task = ConflationTask(
                description="Conflating road networks...",
                source_layer=source_layer,
                destination_layer=destination_layer,
                fields=attributes,
                pattern=road_pattern,
                threshold=threshold
            )

            progress = QProgressDialog(
                "Conflating road networks...", "Cancel", 0, 100, self.dlg
                )
            progress.setWindowTitle("Conflation Progress")
            progress.setWindowModality(Qt.WindowModal)
            progress.setAutoClose(False)
            progress.setAutoReset(False)

            task.progressChanged.connect(lambda value: progress.setValue(int(value)))
            progress.canceled.connect(lambda: task.cancel())

            progress.show()

            task.taskCompleted.connect(lambda: self.conflation_finished(task, output_path, progress))
            task.taskTerminated.connect(lambda: self.conflation_terminated(task, progress))

            QgsApplication.taskManager().addTask(task)
