# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ConflateRoadsDialog
                                 A QGIS plugin
 This plugin conflates road network datasets by matching road segments using geometric and topological similarity metrics, then transfers selected attributes from a reference dataset to a target dataset.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-07-28
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Philip Nyakwaka
        email                : philipnyakwaka24@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from qgis.core import QgsMapLayerProxyModel

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(
    os.path.join(
        os.path.dirname(__file__),
        'conflate_roads_dialog_base.ui'),
    from_imports=True,
    import_from='conflate_roads')


class ConflateRoadsDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(ConflateRoadsDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)

        # only vector layers should be selectable in the layer combo boxes
        self.cmbSourceLayer.setFilters(QgsMapLayerProxyModel.VectorLayer)
        self.cmbDestinationLayer.setFilters(QgsMapLayerProxyModel.VectorLayer)

        # populate the road network pattern combo box with options
        self.cmbRoadPattern.clear()
        self.cmbRoadPattern.addItems([
            "Select a road network pattern...",
            "Hybrid",
            "Tree",
            "Cellular"
        ])
        self.cmbRoadPattern.setCurrentIndex(0)

        # populate attributes when the destination layer changes
        self.cmbDestinationLayer.layerChanged.connect(
            self.populate_destination_fields
        )

        # Populate immediately if a destination layer is already selected
        self.populate_destination_fields(self.cmbDestinationLayer.currentLayer())

        # connect the output file selection button to the file dialog
        self.btnBrowseOutput.clicked.connect(self.select_output_file)

    def populate_destination_fields(self, layer):
        self.cmbAttributes.clear()
        if layer is None:
            return
        fields = layer.fields()
        field_names = [field.name() for field in fields]
        self.cmbAttributes.addItems(field_names)

    def select_output_file(self):
        filename, selected_filter = QtWidgets.QFileDialog.getSaveFileName(
            self,
            "Save Conflated Roads",
            "",
            "GeoPackage (*.gpkg);;Shapefiles (*.shp);;GeoJSON (*.geojson)"
        )
        if filename:
            if selected_filter.startswith("GeoPackage") and not filename.lower().endswith(".gpkg"):
                filename += ".gpkg"

            elif selected_filter.startswith("Shapefiles") and not filename.lower().endswith(".shp"):
                filename += ".shp"

            elif selected_filter.startswith("GeoJSON") and not filename.lower().endswith(".geojson"):
                filename += ".geojson"

            self.txtOutputFile.setText(filename)

    def accept(self):
        # Check if a destination layer is selected
        if self.cmbDestinationLayer.currentLayer() is None:
            QtWidgets.QMessageBox.warning(
                self,
                "Missing Input",
                "Please select a destination road layer."
            )
            return

        # Check if a source layer is selected
        if self.cmbSourceLayer.currentLayer() is None:
            QtWidgets.QMessageBox.warning(
                self,
                "Missing Input",
                "Please select a source road layer."
            )
            return

        # Check if at least one attribute is selected
        if not self.cmbAttributes.checkedItems():
            QtWidgets.QMessageBox.warning(
                self,
                "Missing Input",
                "Please select at least one attribute to transfer."
            )
            return

        # check road pattern selection
        if self.cmbRoadPattern.currentIndex() == 0:
            QtWidgets.QMessageBox.warning(
                self,
                "Missing Input",
                "Please select a road network pattern."
            )
            return

        # check search buffer value
        if self.spnSearchBuffer.value() <= 0:
            QtWidgets.QMessageBox.warning(
                self,
                "Invalid Input",
                "Please enter a positive value for the search buffer."
            )
            return

        # check output file path
        output_path = self.txtOutputFile.text()
        if not output_path:
            QtWidgets.QMessageBox.warning(
                self,
                "Missing Input",
                "Please specify an output file path."
            )
            return

        # check the output folder exists
        output_folder = os.path.dirname(output_path)
        if not os.path.exists(output_folder):
            QtWidgets.QMessageBox.warning(
                self,
                "Invalid Output Path",
                f"The specified output folder does not exist: {output_folder}"
            )
            return

        # check the output format is supported
        if not (output_path.lower().endswith(".gpkg") or
                output_path.lower().endswith(".shp") or
                output_path.lower().endswith(".geojson")):
            QtWidgets.QMessageBox.warning(
                self,
                "Invalid Output Format",
                "The output file must be in one of the following formats:\
                 GeoPackage (.gpkg), Shapefile (.shp), or GeoJSON (.geojson)."
            )
            return
        
        super().accept()
